import {randomBytes} from 'node:crypto';
import type {State,Booking} from './model.js';
import {fail,id,positive,str,clone} from './validation.js';
import {local,instant,stamp,hours,minute,boundary,at,date} from './time.js';
export function restaurant(s:State,rid:any){const r=s.restaurants.find(r=>r.id===id(rid));if(!r)fail('not_found',404);return r;}
export function view(b:Booking){return {reservation_id:b.id,reference:b.reference,restaurant_id:b.restaurant_id,table_id:b.table_ids[0],party_size:b.party_size,status:b.status,starts_at_local:b.starts_at_local,starts_at:stamp(b.start,b.rules.timezone),ends_at:stamp(b.end,b.rules.timezone),created_at:b.created_at};}
export function own(s:State,ref:string,uid:string){const b=s.reservations.find(b=>b.reference===ref&&b.user_id===uid);if(!b)fail('not_found',404);return b;}
export function editable(b:Booking,now:number){if(b.status==='cancelled')fail('reservation_cancelled',409);if(now>=b.start-b.rules.cancellation_cutoff_minutes*60000)fail('cutoff_passed',409);}
export function selection(s:State,input:any){const rid=id(input.restaurant_id),tid=id(input.table_id),p=positive(input.party_size),l=str(input.starts_at_local);local(l);const r=restaurant(s,rid),t=r.tables.find((t:any)=>t.id===tid);if(!t)fail('not_found',404);if(p>t.capacity)fail('party_exceeds_capacity');const start=instant(l,r.timezone),end=start+r.reservation_duration_minutes*60000,h=hours(r,l.slice(0,10)),m=minute(l.slice(11));if(!h||m<minute(h.opens)||m>=minute(h.closes)||start<boundary(l.slice(0,10),minute(h.opens),r.timezone)||end>boundary(l.slice(0,10),minute(h.closes),r.timezone))fail('outside_opening_hours');if((m-minute(h.opens))%r.slot_minutes)fail('not_on_slot_grid');return {restaurant_id:rid,table_ids:[tid],party_size:p,starts_at_local:l,start,end,rules:{timezone:r.timezone,reservation_duration_minutes:r.reservation_duration_minutes,cancellation_cutoff_minutes:r.cancellation_cutoff_minutes}};}
export function overlap(a:Booking,b:Booking){return a.status==='confirmed'&&b.status==='confirmed'&&a.restaurant_id===b.restaurant_id&&a.start<b.end&&b.start<a.end&&a.table_ids.some(t=>b.table_ids.includes(t));}
export function occupancy(s:State,candidates:Booking[]){const ids=new Set(candidates.map(b=>b.id));const others=s.reservations.filter(b=>!ids.has(b.id));for(let i=0;i<candidates.length;i++)if([...others,...candidates.slice(i+1)].some(b=>overlap(candidates[i],b)))fail('table_unavailable',409);}
export function create(s:State,b:any,uid:string,now:number){const selected=selection(s,b);let ref:string;do{ref=randomBytes(6).toString('hex').toUpperCase();}while(s.reservations.some(b=>b.reference===ref));let bid:string;do{bid='res_'+randomBytes(12).toString('hex');}while(s.reservations.some(b=>b.id===bid));const record:Booking={...selected,id:bid,reference:ref,user_id:uid,status:'confirmed',created_at:stamp(now)};occupancy(s,[record]);s.reservations.push(record);return view(record);}
export function amended(s:State,b:Booking,input:any,now:number){editable(b,now);const result={...clone(b),...selection(s,{restaurant_id:b.restaurant_id,table_id:input.table_id===undefined?b.table_ids[0]:input.table_id,party_size:input.party_size===undefined?b.party_size:input.party_size,starts_at_local:input.starts_at_local===undefined?b.starts_at_local:input.starts_at_local})};return result;}
export function moves(s:State,input:any,uid:string,now:number){const ms=input.moves;if(!Array.isArray(ms)||ms.length<1||ms.length>8||ms.some(m=>!m||typeof m!=='object'||Array.isArray(m)||typeof m.reference!=='string')||new Set(ms.map(m=>m.reference)).size!==ms.length)fail();const results:Booking[]=[];let rid;for(const m of ms){const b=own(s,m.reference,uid);if(rid&&rid!==b.restaurant_id)fail();rid=b.restaurant_id;results.push(amended(s,b,m,now));}occupancy(s,results);for(const b of results)s.reservations[s.reservations.findIndex(v=>v.id===b.id)]=b;return {reservations:results.map(view)};}
export function availability(s:State,q:URLSearchParams){const rid=q.get('restaurant_id')??undefined,day=q.get('date')??undefined,party=q.get('party_size');if(day===undefined||party===null||!/^\d+$/.test(party))fail();date(day);const p=positive(Number(party)),r=restaurant(s,rid),h=hours(r,day),slots:any[]=[];if(h)for(let m=minute(h.opens);m<minute(h.closes);m+=r.slot_minutes){const l=at(day,m);let start;try{start=instant(l,r.timezone);}catch(e){if((e as any).code==='invalid_local_time')continue;throw e;}const end=start+r.reservation_duration_minutes*60000;if(end>boundary(day,minute(h.closes),r.timezone))continue;const tids=r.tables.filter((t:any)=>t.capacity>=p&&!s.reservations.some(b=>overlap({...b,id:'',restaurant_id:r.id,table_ids:[t.id],status:'confirmed',start,end},b))).map((t:any)=>t.id);slots.push({starts_at_local:l,starts_at:stamp(start,r.timezone),available_table_ids:tids});}return {restaurant_id:r.id,date:day,timezone:r.timezone,slots};}
