import {createServer,type IncomingMessage} from 'node:http';
import {Fault,fail,object,canonical,clone} from './validation.js';
import {snapshot,replace,transact} from './store.js';
import {account,credential,verify,opaque,authenticate} from './auth.js';
import {fixture,imported} from './serialization.js';
import {restaurant,availability,view,own,editable,create,amended,occupancy,moves} from './domain.js';
async function body(req:IncomingMessage){const chunks:Buffer[]=[];for await(const c of req)chunks.push(Buffer.from(c));try{const raw=Buffer.concat(chunks).toString('utf8');if(!raw&&/^\/reservations\/[^/]+\/cancel(?:\?|$)/.test(req.url??''))return {};return object(JSON.parse(raw));}catch(e){if(e instanceof Fault)throw e;fail('malformed_request',400);}}
async function route(req:IncomingMessage):Promise<[number,any?]>{const method=req.method!,url=new URL(req.url!,'http://localhost'),path=url.pathname;const b=['POST','PATCH'].includes(method)?await body(req):undefined;
if(method==='GET'&&path==='/health')return [200,{status:'ok'}];
if(method==='POST'&&path==='/_test/reset'){replace(await fixture(b));return [204];}
if(method==='GET'&&path==='/_test/export')return [200,{track:'tablekeeper',format_version:1,state:clone(snapshot())}];
if(method==='POST'&&path==='/_test/import'){replace(imported(b));return [204];}
if(method==='POST'&&(path==='/auth/signup'||path==='/auth/login')){const signup=path.endsWith('signup'),a=account(b,signup);if(signup){const c=await credential(a.password);return transact(s=>{if(s.users.some(u=>u.email===a.email))fail('email_taken',409);const user={id:'u_'+opaque().slice(0,32),email:a.email,display_name:a.display_name!,credential:c};const token=opaque();s.users.push(user);s.sessions.push({token,user_id:user.id});return [201,{user_id:user.id,display_name:user.display_name,token}] as [number,any];});}const prior=snapshot().users.find(u=>u.email===a.email);if(!prior||!await verify(a.password,prior.credential))fail('unauthenticated',401);return transact(s=>{const user=s.users.find(u=>u.id===prior.id&&u.email===prior.email&&canonical(u.credential)===canonical(prior.credential));if(!user)fail('unauthenticated',401);const token=opaque();s.sessions.push({token,user_id:user.id});return [200,{user_id:user.id,display_name:user.display_name,token}] as [number,any];});}
if(method==='GET'&&path==='/restaurants')return [200,{restaurants:snapshot().restaurants.map(r=>({id:r.id,name:r.name,timezone:r.timezone}))}];
if(method==='GET'&&path.startsWith('/restaurants/'))return [200,restaurant(snapshot(),decodeURIComponent(path.slice(13)))];
if(method==='GET'&&path==='/availability')return [200,availability(snapshot(),url.searchParams)];
const uid=authenticate(snapshot(),req.headers.authorization);
if(method==='POST'&&['/reservations','/reservation-moves'].includes(path)){const key=req.headers['idempotency-key'];if(key===undefined||key==='')fail('missing_idempotency_key',400);if(typeof key!=='string'||key.length>255)fail();return transact(s=>{const identity=canonical(b),prior=s.receipts.find(r=>r.user_id===uid&&r.method===method&&r.path===path&&r.key===key);if(prior){if(prior.canonical!==identity)fail('idempotency_key_reuse',409);return [200,prior.response] as [number,any];}const response=path==='/reservations'?create(s,b,uid,Date.now()):moves(s,b,uid,Date.now());s.receipts.push({user_id:uid,method,path,key,body:clone(b),canonical:identity,response:clone(response)});return [201,response] as [number,any];});}
if(method==='GET'&&path==='/reservations')return [200,{reservations:snapshot().reservations.filter(b=>b.user_id===uid).sort((a,b)=>b.start-a.start||a.id.localeCompare(b.id)).map(view)}];
const match=/^\/reservations\/([^/]+)(\/cancel)?$/.exec(path);if(match){const reference=decodeURIComponent(match[1]);if(method==='GET'&&!match[2])return [200,view(own(snapshot(),reference,uid))];if((method==='POST'&&match[2])||(method==='PATCH'&&!match[2]))return transact(s=>{const old=own(s,reference,uid);if(method==='POST'){if(old.status!=='cancelled'){editable(old,Date.now());old.status='cancelled';}return [200,view(old)] as [number,any];}const next=amended(s,old,b,Date.now());occupancy(s,[next]);s.reservations[s.reservations.findIndex(v=>v.id===old.id)]=next;return [200,view(next)] as [number,any];});}
fail('not_found',404);}
createServer(async(req,res)=>{try{const [status,value]=await route(req);res.statusCode=status;if(status===204){res.end();return;}res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(value));}catch(e){const f=e instanceof Fault?e:new Fault(500,'internal_error');if(!(e instanceof Fault))console.error('Unexpected request failure',e instanceof Error?e.message:'unknown');res.writeHead(f.status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify({error:{code:f.code,message:f.message}}));}}).listen(Number(process.env.PORT??8080),'0.0.0.0');
